# Replace the text below to customize your site
site_name: projectTCG
site_description: Documentation for Bram van den Dongen
site_author: Bram van den Dongen
copyright: Copyright 2024 Bram van den Dongen - Creative Commons Attribution Non Commercial
  
theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: deep orange
    accent: deep purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Arial
    code: Ubuntu Mono  
  logo: images/yodude.jpg
  favicon: images/yodude.jpg
  features:
    - navigation.instant 
    - content.code.annotate 
nav:
    - 'Overview' :
      - 'Generic rules' : 'GenericRules.md'
    - 'Occultist' :
      - 'Main class' : 'Occultist.md'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.keys
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
